" based on sensible.vim by Tim Pope
" and on vimrc from joaomcteixeira
" with a few additions here and there
"

" Plugins
" Run the following command to install the plugin manager
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"
" gruvbox: colorscheme
" ale: linter
" coc: autocompletion
"
call plug#begin('~/.vim/plugged')

Plug 'gruvbox-community/gruvbox'
Plug 'dense-analysis/ale'

call plug#end()

" colorscheme
colorscheme gruvbox
set background=dark

" syntax highlighting
syntax on

" Remap half PgUp/PgDn to ,d/,c
nnoremap ,d <C-u>
nnoremap ,c <C-d>
" Remap window navigation
" Instead of Ctrl-W + J, do ,J
nnoremap ,j <C-W><C-J>
nnoremap ,k <C-W><C-K>
nnoremap ,l <C-W><C-L>
nnoremap ,h <C-W><C-H>

" allow buffer change with unsaved changed
set hidden

" Shuush
set noerrorbells

" set line numbers
set nu

" Indentation & Spaces
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smartindent

" swap & backup
set noswapfile
set nobackup

" extra column for linters and stuff
set signcolumn=yes

" highlight column
set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=lightgrey

" match long/empty lines
match ErrorMsg '\%>80v.\+'
match ErrorMsg '\s\+$'

" saner backspace key
set backspace=indent,eol,start
" wrap lines when moving with cursor/hl keys
set whichwrap+=<,>,h,l

" Auto-complete with Ctrl-P: ignore included files.
set complete-=i

" regular expressions
set magic

" show matching brackets
set showmatch
set mat=2  " blink time when matching (in 0.1s)

" do not wrap long lines
set nowrap

" tab-completion for file-related tasks
set path+=**
set wildmenu

if !has('nvim') && &ttimeoutlen == -1
  set ttimeout
  set ttimeoutlen=100
endif

" search as you type
set incsearch
" Use <esc><esc> to clear the highlighting of :set hlsearch.
nnoremap <esc><esc> :silent! nohls<cr>

set laststatus=2
set ruler

set scrolloff=5  " move when 5 lines before end of screen
set sidescrolloff=1  " scroll 1 char at a time horizontally (wrap)
set display+=lastline  " do not show @@ after last line

if has('path_extra')
  setglobal tags-=./tags tags-=./tags; tags^=./tags;
endif

if &shell =~# 'fish$' && (v:version < 704 || v:version == 704 && !has('patch276'))
  set shell=/usr/bin/env\ bash
endif

if &history < 1000
  set history=1000
endif
if &tabpagemax < 50
  set tabpagemax=50
endif
if !empty(&viminfo)
  set viminfo^=!
endif
set sessionoptions-=options
set viewoptions-=options

" Load matchit.vim, but only if the user hasn't installed a newer version.
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim
endif

if empty(mapcheck('<C-U>', 'i'))
  inoremap <C-U> <C-G>u<C-U>
endif
if empty(mapcheck('<C-W>', 'i'))
  inoremap <C-W> <C-G>u<C-W>
endif

" vim:set ft=vim et sw=2:

" autocmds

" Delete trailing white space on save, useful for some filetypes ;)
" from github.com/christopheryoung/dotfiles
function! CleanExtraSpaces()
  let save_cursor = getpos(".")
  let old_query = getreg('/')
  silent! %s/\s\+$//e
  call setpos('.', save_cursor)
  call setreg('/', old_query)
endfun

if has("autocmd")
  autocmd BufWritePre *.txt,*.js,*.py,*.wiki,*.sh,*.coffee :call CleanExtraSpaces()
endif
